[package]
name = "swapi_core"
version = "0.1.0"
authors = ["Igor Steblii <igor.stebliy@gmail.com>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
